# Generated by Django 2.1.3 on 2018-11-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='AbsoluteLength',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Area',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='AvgPressure',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='AvgSpeed',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Direction',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Duration',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='EndPressure',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='EndX',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='EndY',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Length',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='MoveType',
            field=models.TextField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='StartPressure',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='StartX',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='StartY',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='TrOrTst',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='UserID',
            field=models.TextField(default='null', max_length=200),
        ),
    ]
