# Generated by Django 2.1.3 on 2018-11-15 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postings', '0003_blogpost_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='ApiPost',
        ),
    ]
