# Generated by Django 2.1.3 on 2018-11-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20181115_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipost',
            name='AvgSize',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='apipost',
            name='EndSize',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='apipost',
            name='StartSize',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
